### ISSUE TITLE
Does not seem to work for current version of sketch

### ISSUE THREAD

**Issue by ignatremizov** [Charimon/iosViews#1]
After installing this app hoping that I could convert my sketch drawings into Core Graphics code, I was disappointed that nothing happened when I ran the plugin. The current version of sketch is 3.3.2. I did exactly like the instructions, but literally nothing happens when I run it. No alert, No message where to save the produced file. Is is possible to update to work with the current version of sketch?

**Comment by Charimon** [comment]
should be working with current version of sketch now, puts stuff into your clipboard

**Comment by tbaranes** [comment]
I'm getting nothing in the clipboard, is it still working?
